### ISSUE TITLE
Delete this repo?

### ISSUE THREAD

**Issue by ghost** [countcain/graphql-rust#1]
Please delete this repo. It gets indexed by the web crawlers and gives false hope to people searching for a graphql implementation in rust.

**Comment by jeremyjh** [comment]
@countcain Why have you published "Hello World" to crates.io under the pseudonym `graphql-rust` ?

**Comment by jeffersd** [comment]
"gives false hope", yep, lol. It's also [GraphQL in Crates.io](https://crates.io/crates/GraphQL).

**Comment by ghost** [comment]
Yes...Now there is the juniper crate provides an implementation for us. It would have been good if the name graphql was still available in crates.io. @countcain is pure evil..  :smiling_imp:

**Comment by jeremyjh** [comment]
I'm guessing its for his resume. He knows recruiters never actually look at the code. (I do).

**Comment by countcain** [comment]
Guys I am really sorry that I occupied this name for such a long time. The crates name will be transferred to the juniper team.
@jeremyjh BTW I never branded myself as a Rust-er to recruiters/companies. I am just a normal JS developer.

I will try to contribute to juniper one day!

**Comment by ghost** [comment]
@countcain thanks. The pure evil stuff was just for fun 😄 btw.
